version: "3"

services:
  # generic mysql database
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
        #    networks:
        #      - internal

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-conf/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
    restart: unless-stopped

  phpadmin:
    image: phpmyadmin
    depends_on:
      - db
        #    links:
        #      - db
    restart: always
    environment:
      PMA_HOST: db
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: admin.db.local
      #      PMA_USER: root
      #      PMA_PASSWORD: root_password
      UPLOAD_LIMIT: 300M
      #    ports:
      #      - "8080:80"
        #    networks:
        #      - internal
        #      - external
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini



networks:
  default:
    external:
      name: nginx-proxy

volumes:
  db-data:
