version: "3"

services:
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal

  drupal:
    image: adoah/aidockerfiles:simpleImg-fpm
    container_name: drupal
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - drupal-data:/app/web

  webserver:
    image: nginx:alpine
    container_name: webserver
    #    depends_on:
    #      - drupal
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - drupal-data:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - external

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  drupal-data:
  db-data:
